ARG BASE_IMAGE
FROM ${BASE_IMAGE}
USER root
COPY token_updater/browser_extensions.py /app/token_updater/browser_extensions.py
COPY deploy/sgp011-yescaptcha/patch_live_login_worker_key.py /tmp/patch_live_login_worker_key.py
RUN python /tmp/patch_live_login_worker_key.py /app/token_updater/login_worker.py \
    && chmod 0644 /app/token_updater/browser_extensions.py /app/token_updater/login_worker.py
ARG WORKER_UID
USER ${WORKER_UID}:12000
