ARG BASE_IMAGE
FROM ${BASE_IMAGE}
ARG WORKER_UID
USER root
COPY token_updater/browser_extensions.py /app/token_updater/browser_extensions.py
COPY deploy/sgp011-yescaptcha/patch_live_login_worker_extension.py /tmp/patch_login_worker_extension.py
RUN python /tmp/patch_login_worker_extension.py /app/token_updater/login_worker.py \
    && chmod 0644 /app/token_updater/browser_extensions.py /app/token_updater/login_worker.py
USER ${WORKER_UID}:12000
